language: julia
notifications:
  email: false
julia:
- 1.0
- 1.6
- nightly
os:
- linux
arch:
- x64
cache:
  directories:
  - "~/.julia/artifacts"
env:
  global:
    - fk=fakekey
    - secure: "EDLo6Tk7BSynJrDxVwRiMGg4j5MlqjtUjuRX42MJqVK45r+m9zso8Qc595z1rOd/7BrqmRmBzbgMTypj4CGIMEA++kdb70DDcfjiAKWZmaxFUE55DEr8rZKaEP0Rf7Bkp3iopHyVkxCFIEgXEnUJYepiTFsDOQadvXWFJA9H90P1TvaxRzpqpcOsgM1SEyIb2ENBPlMW/F3IH6hWhGvUrDKA9jOUabf/dxwguyPSU9HDSeCfatfxd8RvPgs2XnjUUyWxYHcUUeh6eBGXsUc5NWxVABZZ4Q7aChDCzQIY0//cL9vqZV9BaaiLJCkIxfyRO5iouSmOEuSJ7fzIKJx2PKGTThWpzvcb2zkqLS2KR5hFE3WR2rrAiMrfXt8lFhej5hOPmavP9wGvh8ItlxJod4ZykcotPGjQ5E9t2bu5YToR3LOWTdKd5BZ/AlNyr0hdqtrx1Q7qXdCoCT1xsa+2owRBjzBRZla/nAK+THFNIuTwuHQ4J2jsha1E8OK3DtyZ6HRuvT0Luepli1VyejbhDuEblZ/ylP2p7TFZRBm8pLSxKAGl+Kf0OtJ3Y9LF9Z7029NNgtaaSCw7RvRVeRzHypBbaMKQVsBhM86uOoSbMl77cYQQ8jciRt1UaM2EzPg6XB8jkFqVDTlZ5d7PEtEBk/uusot7dX35STMBkd2m/BU="
jobs:
  fast_finish: true
  allow_failures:
  - julia: nightly
after_success:
- |
  julia -e '
    using Pkg
    Pkg.add("Coverage")
    using Coverage
    Codecov.submit(process_folder())'
- |-
  julia -e '
    using Pkg
    Pkg.add("Coverage")
    using Coverage
    Coveralls.submit(process_folder())'
